const applications = [
  {
    id: 1,
    company: "Google",
    position: "Frontend Engineer",
    status: "Applied",
    appliedDate: "2025-12-10T09:30:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "Mountain View, CA",
    work: "On-Site",
    type: "Full-time",
    notes: "Referred by alumni",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-10T09:30:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 2,
    company: "Microsoft",
    position: "Software Engineer",
    status: "Interviewing",
    appliedDate: "2025-12-15T14:00:00.000Z",
    interviewDate: "2026-01-20T10:00:00.000Z",
    rejectedDate: null,
    location: "Redmond, WA",
    work: "On-Site",
    type: "Full-time",
    notes: "Completed technical round",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-15T14:00:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2026-01-10T11:00:00.000Z",
        note: "Moved to interviewing stage",
      },
    ],
  },
  {
    id: 3,
    company: "Spotify",
    position: "UI Engineer",
    status: "Rejected",
    appliedDate: "2025-11-28T16:45:00.000Z",
    interviewDate: "2025-12-05T15:30:00.000Z",
    rejectedDate: "2025-12-12T09:00:00.000Z",
    location: "Remote",
    work: "Remote",
    type: "Contract",
    notes: "Strong portfolio feedback",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-11-28T16:45:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2025-12-05T15:30:00.000Z",
        note: "Scheduled for interview",
      },
      {
        id: 3,
        type: "status_change",
        from: "Interviewing",
        to: "Rejected",
        timestamp: "2025-12-12T09:00:00.000Z",
        note: "Application rejected after interview",
      },
    ],
  },
  {
    id: 4,
    company: "Stripe",
    position: "Frontend Developer",
    status: "Offer",
    appliedDate: "2025-12-20T11:20:00.000Z",
    interviewDate: "2026-01-08T14:00:00.000Z",
    rejectedDate: null,
    location: "San Francisco, CA",
    work: "On-Site",
    type: "Full-time",
    notes: "Offer expires in 2 weeks",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-20T11:20:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2026-01-03T10:00:00.000Z",
        note: "Invited for interview",
      },
      {
        id: 3,
        type: "status_change",
        from: "Interviewing",
        to: "Offer",
        timestamp: "2026-01-15T16:30:00.000Z",
        note: "Received job offer",
      },
    ],
  },
  {
    id: 5,
    company: "Airbnb",
    position: "React Engineer",
    status: "Applied",
    appliedDate: "2025-12-05T08:15:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "Remote",
    work: "Remote",
    type: "Full-time",
    notes: "",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-05T08:15:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 6,
    company: "Netflix",
    position: "Senior Frontend Engineer",
    status: "Interviewing",
    appliedDate: "2025-11-15T10:00:00.000Z",
    interviewDate: "2026-01-25T13:00:00.000Z",
    rejectedDate: null,
    location: "Los Gatos, CA",
    work: "Hybrid",
    type: "Full-time",
    notes: "Final round scheduled",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-11-15T10:00:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2025-12-22T14:30:00.000Z",
        note: "Passed initial screening",
      },
    ],
  },
  {
    id: 7,
    company: "Meta",
    position: "Frontend Software Engineer",
    status: "Rejected",
    appliedDate: "2025-10-20T09:45:00.000Z",
    interviewDate: "2025-11-10T16:00:00.000Z",
    rejectedDate: "2025-11-18T10:30:00.000Z",
    location: "Menlo Park, CA",
    work: "On-Site",
    type: "Full-time",
    notes: "Didn't pass system design round",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-10-20T09:45:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2025-11-10T16:00:00.000Z",
        note: "Interview scheduled",
      },
      {
        id: 3,
        type: "status_change",
        from: "Interviewing",
        to: "Rejected",
        timestamp: "2025-11-18T10:30:00.000Z",
        note: "Not moving forward",
      },
    ],
  },
  {
    id: 8,
    company: "Amazon",
    position: "Web Development Engineer",
    status: "Applied",
    appliedDate: "2025-12-28T15:20:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "Seattle, WA",
    work: "On-Site",
    type: "Full-time",
    notes: "Applied through company portal",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-28T15:20:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 9,
    company: "Apple",
    position: "UI/UX Engineer",
    status: "Applied",
    appliedDate: "2026-01-02T11:00:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "Cupertino, CA",
    work: "On-Site",
    type: "Full-time",
    notes: "Interested in Apple Wallet team",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2026-01-02T11:00:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 10,
    company: "Uber",
    position: "Frontend Engineer",
    status: "Interviewing",
    appliedDate: "2025-11-30T13:15:00.000Z",
    interviewDate: "2026-01-22T09:30:00.000Z",
    rejectedDate: null,
    location: "San Francisco, CA",
    work: "Hybrid",
    type: "Full-time",
    notes: "Working on rider app team",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-11-30T13:15:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2026-01-12T10:00:00.000Z",
        note: "Phone screen scheduled",
      },
    ],
  },
  {
    id: 11,
    company: "Shopify",
    position: "Full Stack Developer",
    status: "Applied",
    appliedDate: "2025-12-18T10:30:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "Ottawa, Canada",
    work: "Remote",
    type: "Full-time",
    notes: "E-commerce platform interest",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-18T10:30:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 12,
    company: "Tesla",
    position: "Software Engineer - UI",
    status: "Rejected",
    appliedDate: "2025-11-05T14:45:00.000Z",
    interviewDate: null,
    rejectedDate: "2025-11-12T09:15:00.000Z",
    location: "Austin, TX",
    work: "On-Site",
    type: "Full-time",
    notes: "Position filled internally",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-11-05T14:45:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Rejected",
        timestamp: "2025-11-12T09:15:00.000Z",
        note: "Position no longer available",
      },
    ],
  },
  {
    id: 13,
    company: "LinkedIn",
    position: "Staff Frontend Engineer",
    status: "Offer",
    appliedDate: "2025-12-01T09:00:00.000Z",
    interviewDate: "2025-12-20T14:00:00.000Z",
    rejectedDate: null,
    location: "Sunnyvale, CA",
    work: "Hybrid",
    type: "Full-time",
    notes: "Competitive offer package",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-01T09:00:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2025-12-20T14:00:00.000Z",
        note: "Interview completed",
      },
      {
        id: 3,
        type: "status_change",
        from: "Interviewing",
        to: "Offer",
        timestamp: "2026-01-18T11:00:00.000Z",
        note: "Offer received",
      },
    ],
  },
  {
    id: 14,
    company: "Twitter",
    position: "Frontend Developer",
    status: "Applied",
    appliedDate: "2025-12-12T16:00:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "Remote",
    work: "Remote",
    type: "Contract",
    notes: "6-month contract position",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-12T16:00:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 15,
    company: "Adobe",
    position: "Web Developer",
    status: "Interviewing",
    appliedDate: "2025-11-22T11:30:00.000Z",
    interviewDate: "2026-01-24T15:00:00.000Z",
    rejectedDate: null,
    location: "San Jose, CA",
    work: "Hybrid",
    type: "Full-time",
    notes: "Creative Cloud team",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-11-22T11:30:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2026-01-15T09:00:00.000Z",
        note: "Technical assessment passed",
      },
    ],
  },
  {
    id: 16,
    company: "Salesforce",
    position: "Frontend Engineer",
    status: "Applied",
    appliedDate: "2026-01-05T08:45:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "San Francisco, CA",
    work: "Hybrid",
    type: "Full-time",
    notes: "Lightning platform",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2026-01-05T08:45:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 17,
    company: "Dropbox",
    position: "Senior Web Engineer",
    status: "Rejected",
    appliedDate: "2025-10-15T13:20:00.000Z",
    interviewDate: "2025-11-01T10:00:00.000Z",
    rejectedDate: "2025-11-08T14:30:00.000Z",
    location: "Remote",
    work: "Remote",
    type: "Full-time",
    notes: "Strong competition",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-10-15T13:20:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2025-11-01T10:00:00.000Z",
        note: "Initial interview",
      },
      {
        id: 3,
        type: "status_change",
        from: "Interviewing",
        to: "Rejected",
        timestamp: "2025-11-08T14:30:00.000Z",
        note: "Position filled",
      },
    ],
  },
  {
    id: 18,
    company: "GitHub",
    position: "Frontend Developer",
    status: "Applied",
    appliedDate: "2025-12-30T14:10:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "Remote",
    work: "Remote",
    type: "Full-time",
    notes: "Developer platform team",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-30T14:10:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 19,
    company: "Twilio",
    position: "UI Engineer",
    status: "Interviewing",
    appliedDate: "2025-12-08T09:20:00.000Z",
    interviewDate: "2026-01-19T11:30:00.000Z",
    rejectedDate: null,
    location: "San Francisco, CA",
    work: "Remote",
    type: "Full-time",
    notes: "Communications platform",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-08T09:20:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2026-01-05T13:00:00.000Z",
        note: "Moving to interview stage",
      },
    ],
  },
  {
    id: 20,
    company: "Square",
    position: "Frontend Software Engineer",
    status: "Applied",
    appliedDate: "2026-01-08T10:00:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "San Francisco, CA",
    work: "Hybrid",
    type: "Full-time",
    notes: "Payment processing team",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2026-01-08T10:00:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 21,
    company: "Snap Inc",
    position: "Web Engineer",
    status: "Rejected",
    appliedDate: "2025-11-18T15:30:00.000Z",
    interviewDate: null,
    rejectedDate: "2025-11-25T09:00:00.000Z",
    location: "Los Angeles, CA",
    work: "On-Site",
    type: "Full-time",
    notes: "Not enough mobile experience",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-11-18T15:30:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Rejected",
        timestamp: "2025-11-25T09:00:00.000Z",
        note: "Application declined",
      },
    ],
  },
  {
    id: 22,
    company: "Pinterest",
    position: "Frontend Engineer",
    status: "Applied",
    appliedDate: "2025-12-22T12:15:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "San Francisco, CA",
    work: "Hybrid",
    type: "Full-time",
    notes: "Visual discovery platform",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-22T12:15:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 23,
    company: "Reddit",
    position: "Senior Frontend Developer",
    status: "Interviewing",
    appliedDate: "2025-12-02T10:45:00.000Z",
    interviewDate: "2026-01-23T14:30:00.000Z",
    rejectedDate: null,
    location: "Remote",
    work: "Remote",
    type: "Full-time",
    notes: "Community platform team",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-02T10:45:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2026-01-14T16:00:00.000Z",
        note: "Interview scheduled",
      },
    ],
  },
  {
    id: 24,
    company: "Atlassian",
    position: "Frontend Developer",
    status: "Applied",
    appliedDate: "2026-01-10T09:30:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "Sydney, Australia",
    work: "Remote",
    type: "Full-time",
    notes: "Jira team position",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2026-01-10T09:30:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 25,
    company: "Zoom",
    position: "UI/UX Engineer",
    status: "Applied",
    appliedDate: "2025-12-16T11:00:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "San Jose, CA",
    work: "Hybrid",
    type: "Full-time",
    notes: "Video conferencing platform",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-16T11:00:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 26,
    company: "Slack",
    position: "Frontend Engineer",
    status: "Rejected",
    appliedDate: "2025-10-28T14:20:00.000Z",
    interviewDate: "2025-11-15T13:00:00.000Z",
    rejectedDate: "2025-11-22T10:00:00.000Z",
    location: "San Francisco, CA",
    work: "Hybrid",
    type: "Full-time",
    notes: "Cultural fit concerns",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-10-28T14:20:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2025-11-15T13:00:00.000Z",
        note: "Interview conducted",
      },
      {
        id: 3,
        type: "status_change",
        from: "Interviewing",
        to: "Rejected",
        timestamp: "2025-11-22T10:00:00.000Z",
        note: "Not selected",
      },
    ],
  },
  {
    id: 27,
    company: "DocuSign",
    position: "Web Developer",
    status: "Applied",
    appliedDate: "2026-01-12T13:45:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "Seattle, WA",
    work: "Remote",
    type: "Full-time",
    notes: "E-signature platform",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2026-01-12T13:45:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 28,
    company: "Coinbase",
    position: "Frontend Engineer",
    status: "Interviewing",
    appliedDate: "2025-12-10T15:00:00.000Z",
    interviewDate: "2026-01-27T10:30:00.000Z",
    rejectedDate: null,
    location: "Remote",
    work: "Remote",
    type: "Full-time",
    notes: "Crypto exchange platform",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-10T15:00:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2026-01-16T14:00:00.000Z",
        note: "Technical interview scheduled",
      },
    ],
  },
  {
    id: 29,
    company: "Robinhood",
    position: "Senior Frontend Developer",
    status: "Applied",
    appliedDate: "2026-01-15T10:20:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "Menlo Park, CA",
    work: "Hybrid",
    type: "Full-time",
    notes: "Trading platform team",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2026-01-15T10:20:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 30,
    company: "DoorDash",
    position: "Frontend Software Engineer",
    status: "Applied",
    appliedDate: "2025-12-27T09:00:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "San Francisco, CA",
    work: "Hybrid",
    type: "Full-time",
    notes: "Consumer app team",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-27T09:00:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 31,
    company: "Lyft",
    position: "Web Engineer",
    status: "Rejected",
    appliedDate: "2025-11-10T12:30:00.000Z",
    interviewDate: null,
    rejectedDate: "2025-11-17T15:00:00.000Z",
    location: "San Francisco, CA",
    work: "On-Site",
    type: "Full-time",
    notes: "Resume didn't match requirements",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-11-10T12:30:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Rejected",
        timestamp: "2025-11-17T15:00:00.000Z",
        note: "Application not selected",
      },
    ],
  },
  {
    id: 32,
    company: "Notion",
    position: "Frontend Developer",
    status: "Interviewing",
    appliedDate: "2025-12-14T11:15:00.000Z",
    interviewDate: "2026-01-28T13:00:00.000Z",
    rejectedDate: null,
    location: "Remote",
    work: "Remote",
    type: "Full-time",
    notes: "Productivity tools team",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-14T11:15:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2026-01-17T09:30:00.000Z",
        note: "First round completed",
      },
    ],
  },
  {
    id: 33,
    company: "Figma",
    position: "UI Engineer",
    status: "Applied",
    appliedDate: "2026-01-18T14:40:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "San Francisco, CA",
    work: "Hybrid",
    type: "Full-time",
    notes: "Design tools platform",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2026-01-18T14:40:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 34,
    company: "Asana",
    position: "Frontend Engineer",
    status: "Applied",
    appliedDate: "2026-01-06T10:50:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "San Francisco, CA",
    work: "Remote",
    type: "Full-time",
    notes: "Project management tools",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2026-01-06T10:50:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 35,
    company: "Datadog",
    position: "Senior Web Developer",
    status: "Interviewing",
    appliedDate: "2025-12-04T08:30:00.000Z",
    interviewDate: "2026-01-21T15:30:00.000Z",
    rejectedDate: null,
    location: "New York, NY",
    work: "Hybrid",
    type: "Full-time",
    notes: "Monitoring platform team",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-04T08:30:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2026-01-11T12:00:00.000Z",
        note: "Screening call completed",
      },
    ],
  },
  {
    id: 36,
    company: "HubSpot",
    position: "Frontend Developer",
    status: "Applied",
    appliedDate: "2025-12-24T16:20:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "Boston, MA",
    work: "Remote",
    type: "Full-time",
    notes: "CRM platform",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-12-24T16:20:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 37,
    company: "Canva",
    position: "Web Engineer",
    status: "Applied",
    appliedDate: "2026-01-14T09:10:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "Sydney, Australia",
    work: "Remote",
    type: "Full-time",
    notes: "Design platform team",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2026-01-14T09:10:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 38,
    company: "Snowflake",
    position: "Frontend Engineer",
    status: "Rejected",
    appliedDate: "2025-11-02T13:00:00.000Z",
    interviewDate: "2025-11-20T11:00:00.000Z",
    rejectedDate: "2025-11-28T14:00:00.000Z",
    location: "San Mateo, CA",
    work: "On-Site",
    type: "Full-time",
    notes: "Looking for more cloud experience",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-11-02T13:00:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2025-11-20T11:00:00.000Z",
        note: "Technical interview",
      },
      {
        id: 3,
        type: "status_change",
        from: "Interviewing",
        to: "Rejected",
        timestamp: "2025-11-28T14:00:00.000Z",
        note: "Not proceeding",
      },
    ],
  },
  {
    id: 39,
    company: "MongoDB",
    position: "UI Developer",
    status: "Applied",
    appliedDate: "2026-01-20T11:30:00.000Z",
    interviewDate: null,
    rejectedDate: null,
    location: "New York, NY",
    work: "Hybrid",
    type: "Full-time",
    notes: "Database platform UI",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2026-01-20T11:30:00.000Z",
        note: "Application submitted",
      },
    ],
  },
  {
    id: 40,
    company: "Cloudflare",
    position: "Frontend Software Engineer",
    status: "Offer",
    appliedDate: "2025-11-25T10:15:00.000Z",
    interviewDate: "2025-12-18T14:30:00.000Z",
    rejectedDate: null,
    location: "Austin, TX",
    work: "Remote",
    type: "Full-time",
    notes: "Strong compensation package",
    activities: [
      {
        id: 1,
        type: "created",
        timestamp: "2025-11-25T10:15:00.000Z",
        note: "Application submitted",
      },
      {
        id: 2,
        type: "status_change",
        from: "Applied",
        to: "Interviewing",
        timestamp: "2025-12-18T14:30:00.000Z",
        note: "Interview process started",
      },
      {
        id: 3,
        type: "status_change",
        from: "Interviewing",
        to: "Offer",
        timestamp: "2026-01-19T10:00:00.000Z",
        note: "Offer extended",
      },
    ],
  },
];

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  const { id } = req.query;
  const appId = parseInt(id);
  const index = applications.findIndex((a) => a.id === appId);

  if (index === -1) {
    return res.status(404).json({ message: 'Application not found' });
  }

  if (req.method === 'GET') {
    return res.status(200).json(applications[index]);
  }

  if (req.method === 'PUT') {
    applications[index] = {
      ...applications[index],
      ...req.body,
    };
    return res.status(200).json(applications[index]);
  }

  if (req.method === 'DELETE') {
    const deleted = applications.splice(index, 1);
    return res.status(200).json(deleted[0]);
  }

  return res.status(405).json({ message: 'Method not allowed' });
}